<a href="https://colab.research.google.com/github/gabrieldilay/mvp-estudo-faturamento/blob/main/mvp_estudo_faturamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introdução
O trabalho MVP tem como objetivo desenvolver um **modelo de previsão de faturamento** utilizando o conjunto de dados **Rossmann Store Sales**, disponibilizado no Kaggle. Este dataset reúne informações diárias de vendas em milhares de lojas, incluindo variáveis relacionadas a calendário (feriados, fins de semana, promoções, sazonalidade), concorrência e comportamento de clientes.  

O problema proposto enquadra-se na categoria de **regressão / previsão de séries temporais (forecasting)**, uma vez que a variável-alvo corresponde ao valor de vendas diárias. Para sua resolução, foram aplicadas diferentes técnicas de aprendizado supervisionado, modelos de séries temporais clássicos e regressões regularizadas, além de baselines simples para comparação.  

A escolha desta temática justifica-se pela sua relevância tanto acadêmica quanto prática. Do ponto de vista acadêmico, o estudo permite explorar diferentes paradigmas de modelagem, validar métricas de desempenho e analisar limitações de cada abordagem. Do ponto de vista profissional, demonstra-se o potencial de tais técnicas para apoiar a **tomada de decisão baseada em dados**, gerando valor em atividades de previsão de receita, definição de estratégias comerciais e gestão de operações.  

Assim, este MVP busca não apenas atender aos requisitos da disciplina de Data Science & Analytics, mas também servir como **prova de conceito aplicável ao mercado**, com possibilidade de integração em dashboards corporativos e uso em portfólios profissionais.


**Aluno:** Gabriel Dilay de Oliveira


**Matrícula:** 4052025001828

In [ ]:

# SETUP + CARGA DOS DADOS POR URL

# Seeds e ambiente
import os, random, time, platform, numpy as np, pandas as pd
SEED = 42
os.environ["PYTHONHASHSEED"] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
print("Hardware:", platform.platform())

# Função para baixar do Google Drive por URL pública
#gdown pois lida com links "view?usp=sharing".
!pip -q install gdown

import gdown

def download_from_drive(url: str, out: str):
    """
    Faz download de um arquivo Google Drive (URL pública '.../file/d/<ID>/view?...')
    e salva localmente com o nome 'out'.
    """
    try:
        gdown.download(url=url, output=out, quiet=False, fuzzy=True)
        assert os.path.exists(out), f"Download falhou: {out} não encontrado."
        return out
    except Exception as e:
        raise RuntimeError(f"Falha no download de {url}: {e}")

# URLs públicas
url_train = "https://drive.google.com/file/d/1N9hI0gq31AxS_1N8_ua9YrV2Jf_X43vn/view?usp=sharing"
url_test  = "https://drive.google.com/file/d/1feOAfTaB3sniWHWvfjyQ31iixDk5cO2s/view?usp=sharing"
url_store = "https://drive.google.com/file/d/1PT4R3yX-wSNuPXLMWmfr1gSN5BjzyaAh/view?usp=sharing"

t0 = time.time()
fp_train = download_from_drive(url_train, "train.csv")
fp_test  = download_from_drive(url_test,  "test.csv")
fp_store = download_from_drive(url_store, "store.csv")
print(f"[Tempo] download total: {time.time() - t0:.1f}s")

# Leitura com tipos e parse de datas
# Por que definir dtypes? Economiza memória e padroniza colunas categóricas.
train_dtypes = {
    "Store": "int32",
    "DayOfWeek": "int8",
    "Sales": "int32",
    "Customers": "int32",
    "Open": "int8",
    "Promo": "int8",
    "StateHoliday": "category",
    "SchoolHoliday": "int8"
}
test_dtypes = {
    "Id": "int64",
    "Store": "int32",
    "DayOfWeek": "int8",
    "Open": "float32",
    "Promo": "int8",
    "StateHoliday": "category",
    "SchoolHoliday": "int8"
}
store_dtypes = {
    "Store": "int32",
    "StoreType": "category",
    "Assortment": "category",
    "CompetitionDistance": "float32",
    "CompetitionOpenSinceMonth": "float32",
    "CompetitionOpenSinceYear": "float32",
    "Promo2": "int8",
    "Promo2SinceWeek": "float32",
    "Promo2SinceYear": "float32",
    "PromoInterval": "category"
}

parse_cols = ["Date"]

train = pd.read_csv(fp_train, dtype=train_dtypes, parse_dates=parse_cols)
test  = pd.read_csv(fp_test,  dtype=test_dtypes,  parse_dates=parse_cols)
store = pd.read_csv(fp_store, dtype=store_dtypes)

# Checagens rápidas
def quick_info(name, df):
    print(f"\n=== {name} ===")
    print("shape:", df.shape)
    print("cols:", list(df.columns))
    display(df.head(3))

quick_info("train", train)
quick_info("test",  test)
quick_info("store", store)

# Resumos essenciais (nulos e datas)
print("\nNulos no train:\n", train.isna().sum())
print("\nDatas no train -> min/max:", train["Date"].min(), "→", train["Date"].max())

# Merge básico
# Por que já juntar? Para facilitar EDA e engenharia de atributos com metadados da loja.
df = train.merge(store, on="Store", how="left")
print("\nApós merge (train + store):", df.shape)
display(df.head(3))

# Guardar versões auxiliares:
df_raw   = df.copy()
train_df = df.copy()

print("\n✅ Bloco 1 finalizado: dados baixados por URL, lidos com tipos e integrados (train+store).")


Hardware: Linux-6.6.97+-x86_64-with-glibc2.35


Downloading...
From: https://drive.google.com/uc?id=1N9hI0gq31AxS_1N8_ua9YrV2Jf_X43vn
To: /content/train.csv
100%|██████████| 38.1M/38.1M [00:00<00:00, 102MB/s] 
Downloading...
From: https://drive.google.com/uc?id=1feOAfTaB3sniWHWvfjyQ31iixDk5cO2s
To: /content/test.csv
100%|██████████| 1.43M/1.43M [00:00<00:00, 88.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1PT4R3yX-wSNuPXLMWmfr1gSN5BjzyaAh
To: /content/store.csv
100%|██████████| 45.0k/45.0k [00:00<00:00, 55.4MB/s]


[Tempo] download total: 8.8s

=== train ===
shape: (1017209, 9)
cols: ['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday']


Store  DayOfWeek       Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5 2015-07-31   5263        555     1      1            0   
1      2          5 2015-07-31   6064        625     1      1            0   
2      3          5 2015-07-31   8314        821     1      1            0   

   SchoolHoliday  
0              1  
1              1  
2              1


=== test ===
shape: (41088, 8)
cols: ['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday']


Id  Store  DayOfWeek       Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4 2015-09-17   1.0      1            0              0
1   2      3          4 2015-09-17   1.0      1            0              0
2   3      7          4 2015-09-17   1.0      1            0              0


=== store ===
shape: (1115, 10)
cols: ['Store', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval']


Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a               1270.0                        9.0   
1      2         a          a                570.0                       11.0   
2      3         a          a              14130.0                       12.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2007.0       1             13.0           2010.0   
2                    2006.0       1             14.0           2011.0   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct


Nulos no train:
 Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

Datas no train -> min/max: 2013-01-01 00:00:00 → 2015-07-31 00:00:00

Após merge (train + store): (1017209, 18)


Store  DayOfWeek       Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5 2015-07-31   5263        555     1      1            0   
1      2          5 2015-07-31   6064        625     1      1            0   
2      3          5 2015-07-31   8314        821     1      1            0   

   SchoolHoliday StoreType Assortment  CompetitionDistance  \
0              1         c          a               1270.0   
1              1         a          a                570.0   
2              1         a          a              14130.0   

   CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
0                        9.0                    2008.0       0   
1                       11.0                    2007.0       1   
2                       12.0                    2006.0       1   

   Promo2SinceWeek  Promo2SinceYear    PromoInterval  
0              NaN              NaN              NaN  
1             13.0           2010.0  Jan,Apr,Jul,Oct  
2             14.0           2011.0  Jan,Apr,Jul,Oct


✅ Bloco 1 finalizado: dados baixados por URL, lidos com tipos e integrados (train+store).


In [ ]:

# Preparação & EDA inicial + Split temporal (mensal)

import numpy as np
import pandas as pd


# Filtros coerentes com o problema
# Mantemos apenas dias em que a loja estava aberta e com vendas > 0.
df_work = df[(df["Open"] == 1) & (df["Sales"] > 0)].copy()

# Variáveis de calendário e flags úteis
df_work["Year"]        = df_work["Date"].dt.year
df_work["Month"]       = df_work["Date"].dt.month
df_work["DayName"]     = df_work["Date"].dt.day_name()
df_work["is_weekend"]  = df_work["DayOfWeek"].isin([6, 7]).astype(int)   # 6=sáb, 7=dom
df_work["is_holiday"]  = (df_work["StateHoliday"] != "0").astype(int)    # 'a','b','c' = feriados
df_work["is_promo"]    = df_work["Promo"].astype(int)

print("Shape após filtros (aberta & vendas>0):", df_work.shape)
print("Período de datas:", df_work["Date"].min(), "→", df_work["Date"].max())

# Checagens de nulos em colunas chave
nulls = df_work[["Sales","Customers","Promo","StateHoliday","CompetitionDistance","StoreType","Assortment"]].isna().sum()
print("\nNulos (colunas principais):\n", nulls)

# Análise exploratória simples: médias por grupos (efeito bruto, descritivo)
def group_compare_mean(df_in, flag_col, target="Sales"):
    a = df_in.loc[df_in[flag_col]==1, target].mean()
    b = df_in.loc[df_in[flag_col]==0, target].mean()
    uplift = (a/b - 1.0) * 100.0
    return pd.Series({"media_flag_1": a, "media_flag_0": b, "uplift_%": uplift})

eda_impacts = pd.DataFrame({
    "Promo_vs_SemPromo":     group_compare_mean(df_work, "is_promo"),
    "Fds_vs_Uteis":          group_compare_mean(df_work, "is_weekend"),
    "Feriado_vs_Normal":     group_compare_mean(df_work, "is_holiday")
}).T

# Formata para leitura rápida
fmt = eda_impacts.copy()
fmt["media_flag_1"] = fmt["media_flag_1"].map(lambda x: f"{x:,.0f}")
fmt["media_flag_0"] = fmt["media_flag_0"].map(lambda x: f"{x:,.0f}")
fmt["uplift_%"]     = fmt["uplift_%"].map(lambda x: f"{x:.2f}%")
print("\n💡 Médias e uplift descritivo (vendas diárias por loja):")
display(fmt)

# Agregação mensal (cadeia total)
monthly_chain = (
    df_work.groupby(pd.Grouper(key="Date", freq="MS"))["Sales"]
           .sum()
           .to_frame("Sales_total")
           .sort_index()
)

print("\nAmostra da série mensal (cadeia):")
display(monthly_chain.head(3))
display(monthly_chain.tail(3))
print("Meses totais:", len(monthly_chain))

# Split temporal: últimos 6 meses como validação
# manter um protocolo simples e previsível
val_horizon = 6
train_monthly_chain = monthly_chain.iloc[:-val_horizon].copy()
val_monthly_chain   = monthly_chain.iloc[-val_horizon:].copy()

print("\n=== Split mensal (cadeia) ===")
print("Treino:", train_monthly_chain.index.min().date(), "→", train_monthly_chain.index.max().date(),
      f"({len(train_monthly_chain)} meses)")
print("Val   :", val_monthly_chain.index.min().date(),   "→", val_monthly_chain.index.max().date(),
      f"({len(val_monthly_chain)} meses)")

# Guardar para os próximos blocos
globals().update({
    "df_work": df_work,
    "monthly_chain": monthly_chain,
    "train_monthly_chain": train_monthly_chain,
    "val_monthly_chain": val_monthly_chain
})

print("\n✅ Bloco 2 finalizado: preparação/EDA básica feita e split mensal definido.")


Shape após filtros (aberta & vendas>0): (844338, 24)
Período de datas: 2013-01-01 00:00:00 → 2015-07-31 00:00:00

Nulos (colunas principais):
 Sales                     0
Customers                 0
Promo                     0
StateHoliday              0
CompetitionDistance    2186
StoreType                 0
Assortment                0
dtype: int64

💡 Médias e uplift descritivo (vendas diárias por loja):


media_flag_1 media_flag_0 uplift_%
Promo_vs_SemPromo        8,229        5,930   38.77%
Fds_vs_Uteis             5,932        7,173  -17.30%
Feriado_vs_Normal        8,809        6,954   26.67%


Amostra da série mensal (cadeia):


Sales_total
Date                   
2013-01-01    180132207
2013-02-01    171534275
2013-03-01    201180369

Sales_total
Date                   
2015-05-01    189143897
2015-06-01    207363373
2015-07-01    212322616

Meses totais: 31

=== Split mensal (cadeia) ===
Treino: 2013-01-01 → 2015-01-01 (25 meses)
Val   : 2015-02-01 → 2015-07-01 (6 meses)

✅ Bloco 2 finalizado: preparação/EDA básica feita e split mensal definido.


**Prox passo:** Vou avaliar duas abordagens simples para a série mensal:

1 - Naive sazonal (lag-12): cada mês é previsto igual ao mesmo mês do ano anterior.

2 - Ridge com poucas features (ano, mês, lag-12, diferença mensal), para capturar tendência e sazonalidade de forma simples.

In [ ]:

#  Baselines mensais: Naive sazonal e Ridge

import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge
from sklearn.model_selection import TimeSeriesSplit, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


# Preparação: X/y para treino e validação (mensal)

dfM = monthly_chain.copy()
dfM['Year']   = dfM.index.year
dfM['MonthN'] = dfM.index.month
dfM['lag_12'] = dfM['Sales_total'].shift(12)
dfM['diff_1'] = dfM['Sales_total'].diff(1)

X_cols = ['Year','MonthN','lag_12','diff_1']
y_col  = 'Sales_total'

X_all = dfM[X_cols]
y_all = dfM[y_col]

X_train = X_all.loc[train_monthly_chain.index]
y_train = y_all.loc[train_monthly_chain.index]
X_val   = X_all.loc[val_monthly_chain.index]
y_val   = y_all.loc[val_monthly_chain.index]


# 2) Baseline A: Naive sazonal (lag-12)
#    Ideia: previsão do mês t = valor do mês t-12
# Construo as previsões só se existir histórico 12 meses antes
y_pred_naive = []
for dt in X_val.index:
    prev_yr = dt - pd.offsets.DateOffset(years=1)
    if prev_yr in y_all.index:
        y_pred_naive.append(y_all.loc[prev_yr])
    else:
        # fallback: usa último valor conhecido
        y_pred_naive.append(y_train.iloc[-1])

y_pred_naive = pd.Series(y_pred_naive, index=X_val.index, name='y_pred_naive')

mae_n  = mean_absolute_error(y_val, y_pred_naive)
rmse_n = np.sqrt(mean_squared_error(y_val, y_pred_naive))
mape_n = (np.abs((y_val - y_pred_naive)/y_val).mean())*100
r2_n   = r2_score(y_val, y_pred_naive)


# Baseline B: Ridge simples (com pré-processamento)
#    Por quê: regularização ajuda em série curta; inclui trend e sazonalidade (MonthN)
# Pré-processamento: imputo numéricos (lag/diff) e padronizo
pre = ColumnTransformer([
    ("num", Pipeline([
        ("imp", SimpleImputer(strategy="median")),
        ("sc",  StandardScaler())
    ]), X_cols)
])

ridge = Ridge(random_state=SEED)

pipe = Pipeline([
    ("prep", pre),
    ("model", ridge)
])

# TSSplit curto para ser rápido e sem vazamento
tscv = TimeSeriesSplit(n_splits=3)

# Grid pequeno
param_grid = {"model__alpha": [0.1, 1.0, 3.0, 10.0]}

gs = GridSearchCV(
    pipe, param_grid=param_grid,
    scoring="neg_root_mean_squared_error",
    cv=tscv, n_jobs=-1
)
gs.fit(X_train, y_train)

y_pred_ridge = pd.Series(gs.predict(X_val), index=X_val.index, name='y_pred_ridge')

mae_r  = mean_absolute_error(y_val, y_pred_ridge)
rmse_r = np.sqrt(mean_squared_error(y_val, y_pred_ridge))
mape_r = (np.abs((y_val - y_pred_ridge)/y_val).mean())*100
r2_r   = r2_score(y_val, y_pred_ridge)


# Comparação rápida

comp = pd.DataFrame({
    "Real": y_val,
    "Naive12": y_pred_naive,
    "Ridge": y_pred_ridge
})
metrics = pd.DataFrame({
    "Modelo": ["Naive-12","Ridge"],
    "MAE":  [mae_n, mae_r],
    "RMSE": [rmse_n, rmse_r],
    "MAPE(%)":[mape_n, mape_r],
    "R²":   [r2_n, r2_r]
})

print("Melhor alpha (Ridge):", gs.best_params_["model__alpha"])
print("\n Métricas (holdout mensal – últimos 6 meses):")
display(metrics)

print("\n Mês a mês (validação):")
display(comp.round(2))


🔧 Melhor alpha (Ridge): 10.0

📊 Métricas (holdout mensal – últimos 6 meses):


Modelo           MAE          RMSE   MAPE(%)        R²
0  Naive-12  1.298842e+07  1.815843e+07  6.264416 -1.420406
1     Ridge  1.368070e+07  1.587887e+07  6.700497 -0.850848


🗓️ Mês a mês (validação):


Real    Naive12         Ridge
Date                                          
2015-02-01  178275458  178924677  1.771209e+08
2015-03-01  205631683  193019854  1.943566e+08
2015-04-01  197918886  194544977  1.811647e+08
2015-05-01  189143897  194693257  1.805025e+08
2015-06-01  207363373  190047051  1.902122e+08
2015-07-01  212322616  173892707  1.852149e+08

**Prox passo:** Agora a intenção é consolidar as previsões do Naive sazonal e da Ridge em horizontes mais longos.
A ideia é somar os valores dos últimos 6 meses (holdout) para avaliar o erro semestral, e também projetar para 12 meses (quando possível), simulando uma previsão anual.

In [ ]:

# Consolidação (semestre e ano)


# Consolidação semestral (últimos 6 meses do holdout)
real_semestre     = y_val.sum()
naive_semestre    = y_pred_naive.sum()
ridge_semestre    = y_pred_ridge.sum()

err_abs_naive = abs(real_semestre - naive_semestre)
err_perc_naive = err_abs_naive / real_semestre * 100

err_abs_ridge = abs(real_semestre - ridge_semestre)
err_perc_ridge = err_abs_ridge / real_semestre * 100

print("Consolidação semestral (últimos 6 meses - holdout)")
print("Real     :", f"{real_semestre:,.0f}")
print("Naive-12 :", f"{naive_semestre:,.0f}", f"(Erro: {err_abs_naive:,.0f} | {err_perc_naive:.2f}%)")
print("Ridge    :", f"{ridge_semestre:,.0f}", f"(Erro: {err_abs_ridge:,.0f} | {err_perc_ridge:.2f}%)")

# --- 2) Projeção anual (12 meses) ---
# Aqui não temos 12 meses de holdout, mas podemos simular previsão anual
# repetindo o horizonte de 6 meses à frente (ou usando forecast automático depois).
# Por simplicidade: extrapolo somando o semestre previsto * 2.
naive_ano = naive_semestre * 2
ridge_ano = ridge_semestre * 2

print("\n Consolidação anual (simulação = semestre x2)")
print("Naive-12 :", f"{naive_ano:,.0f}")
print("Ridge    :", f"{ridge_ano:,.0f}")


📦 Consolidação semestral (últimos 6 meses - holdout)
Real     : 1,190,655,913
Naive-12 : 1,125,122,523 (Erro: 65,533,390 | 5.50%)
Ridge    : 1,108,571,709 (Erro: 82,084,204 | 6.89%)

📦 Consolidação anual (simulação = semestre x2)
Naive-12 : 2,250,245,046
Ridge    : 2,217,143,418


*os resultados mostram que o naive-12 teve erro menor no semestre (5,5%) que a ridge (6,9%), mas ambos são competitivos em nível estratégico.*

**Prox passo:** agora vou para os modelos diários supervisionados, que exploram melhor os dados tabulares: regressão linear, árvore de regressão, random forest, xgboost, knn

In [ ]:

# Árvores/Boosting

import numpy as np, pandas as pd, gc
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb

# Features essenciais (numéricas/categ. pequenas)
cols = ["Store","DayOfWeek","Promo","SchoolHoliday","StateHoliday",
        "Year","Month","is_weekend","Customers","CompetitionDistance","Sales"]
dfA = df_work[cols].copy()

# Codificação inteira para StateHoliday
#    '0'->0, 'a'->1, 'b'->2, 'c'->3
map_hol = {"0":0, "a":1, "b":2, "c":3}
dfA["StateHoliday"] = dfA["StateHoliday"].astype(str).map(map_hol).fillna(0).astype("int8")

# Imputação simples para CompetitionDistance e tipos compactos
dfA["CompetitionDistance"] = dfA["CompetitionDistance"].astype("float32").fillna(dfA["CompetitionDistance"].median())
for c in ["Store","DayOfWeek","Promo","SchoolHoliday","Year","Month","is_weekend"]:
    dfA[c] = dfA[c].astype("int32")
dfA["Customers"] = dfA["Customers"].astype("int32")
dfA["Sales"]     = dfA["Sales"].astype("int32")

# Split temporal (80/20)
X = dfA.drop(columns=["Sales"])
y = dfA["Sales"]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, shuffle=False)

def eval_reg(name, model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    mae  = mean_absolute_error(y_val, y_pred)
    rmse = float(np.sqrt(mean_squared_error(y_val, y_pred)))
    mape = float(np.mean(np.abs((y_val - y_pred)/y_val))*100)
    r2   = r2_score(y_val, y_pred)
    return name, mae, rmse, mape, r2

# 5) Modelos
res = []

tree = DecisionTreeRegressor(max_depth=10, random_state=SEED)
res.append(eval_reg("Árvore (max_depth=10)", tree))
del tree; gc.collect()

rf = RandomForestRegressor(n_estimators=150, max_depth=None, n_jobs=-1, random_state=SEED)
res.append(eval_reg("RandomForest (n=150)", rf))
del rf; gc.collect()

xg = xgb.XGBRegressor(
    n_estimators=400, max_depth=8, learning_rate=0.08,
    subsample=0.7, colsample_bytree=0.7,
    tree_method="hist", random_state=SEED, n_jobs=-1
)
res.append(eval_reg("XGBoost (leve)", xg))

df_resA = pd.DataFrame(res, columns=["Modelo","MAE","RMSE","MAPE(%)","R²"]).sort_values("RMSE")
display(df_resA.head())


Modelo         MAE         RMSE    MAPE(%)        R²
1   RandomForest (n=150)  363.624975   548.272040   5.943100  0.966628
2         XGBoost (leve)  436.019043   612.876568   7.070861  0.958300
0  Árvore (max_depth=10)  881.788772  1205.604703  14.410608  0.838637

✅ 5A ok (versão leve).


In [ ]:

# Linear/KNN com amostra + OneHot sparse

import numpy as np, pandas as pd, gc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# 1) Seleção e amostra
cols = ["Store","DayOfWeek","Promo","SchoolHoliday","StateHoliday",
        "Year","Month","is_weekend","Customers","CompetitionDistance","Sales"]
dfB = df_work[cols].copy()

# Amostra estratificada por mês
dfB = dfB.sample(frac=0.25, random_state=SEED)

# 2) Pré-processamento leve:
#    - cat: OneHotEncoder sparse para StateHoliday
#    - num: imputação simples; sem scaler para não densificar
cat_cols = ["StateHoliday"]
num_cols = [c for c in dfB.columns if c not in (cat_cols + ["Sales"])]

X = dfB.drop(columns=["Sales"])
y = dfB["Sales"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, shuffle=False)

pre = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore", sparse_output=True), cat_cols),
        ("num", SimpleImputer(strategy="median"), num_cols)
    ],
    remainder="drop",
    sparse_threshold=1.0
)

def eval_pipe(name, est):
    pipe = Pipeline([("prep", pre), ("model", est)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_val)
    mae  = mean_absolute_error(y_val, y_pred)
    rmse = float(np.sqrt(mean_squared_error(y_val, y_pred)))
    mape = float(np.mean(np.abs((y_val - y_pred)/y_val))*100)
    r2   = r2_score(y_val, y_pred)
    return name, mae, rmse, mape, r2

res = []
res.append(eval_pipe("Reg Linear (sparse OneHot)", LinearRegression()))
# KNN em amostra
res.append(eval_pipe("KNN (k=5, amostra 25%)", KNeighborsRegressor(n_neighbors=5)))

df_resB = pd.DataFrame(res, columns=["Modelo","MAE","RMSE","MAPE(%)","R²"]).sort_values("RMSE")
display(df_resB.head())
print("ok")


Modelo          MAE         RMSE    MAPE(%)        R²
1      KNN (k=5, amostra 25%)   491.497278   745.334452   7.108119  0.942777
0  Reg Linear (sparse OneHot)  1123.851225  1580.142025  17.810700  0.742805

✅ 5B ok (amostra+sparse).


**Random Forest (n=150)** → melhor desempenho geral, com MAE 363, RMSE 548, MAPE 5,94%, R² 0,9666.

**XGBoost (leve)**→ também performou bem, mas ficou atrás do Random Forest no RMSE, com MAPE 7,07% e R² 0,9583.

**Árvore de Regressão** → resultado inferior, com MAPE 14,41% e R² 0,83, servindo mais como baseline para modelos de árvore.

**KNN (25% amostra)** → desempenho razoável, com MAPE 7,10% e R² 0,94, mas mais custoso computacionalmente.

**Regressão Linear (sparse OneHot)** → foi o pior modelo, com MAPE 17,8% e R² 0,74, reforçando que relações não-lineares predominam nos dados.

*O Random Forest se destacou como modelo mais robusto no granular diário, com erro percentual médio próximo de 6%, o que é bastante satisfatório.*

*O XGBoost segue como forte candidato, principalmente se otimizarmos hiperparâmetros (que será o foco do Bloco 6).*

*Lineares não capturaram bem as relações complexas, enquanto KNN ficou no meio-termo, mas com limitações de escalabilidade.*

**Prox passo:** otimizar hiperparâmetros do XGBoost no nível diário com busca aleatória e TimeSeriesSplit.
Parâmetros a explorar: max_depth, learning_rate, subsample, colsample_bytree, n_estimators.
Métrica de busca: RMSE (negativo).Depois avaliar no holdout (20% final)

In [ ]:

# Tuning do XGBoost

import numpy as np, pandas as pd, gc
from sklearn.model_selection import train_test_split, RandomizedSearchCV, TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from scipy.stats import randint, uniform
import xgboost as xgb

# Recria features "leves"
cols = ["Store","DayOfWeek","Promo","SchoolHoliday","StateHoliday",
        "Year","Month","is_weekend","Customers","CompetitionDistance","Sales"]
dfX = df_work[cols].copy()

map_hol = {"0":0, "a":1, "b":2, "c":3}
dfX["StateHoliday"] = dfX["StateHoliday"].astype(str).map(map_hol).fillna(0).astype("int8")
dfX["CompetitionDistance"] = dfX["CompetitionDistance"].astype("float32").fillna(dfX["CompetitionDistance"].median())

for c in ["Store","DayOfWeek","Promo","SchoolHoliday","Year","Month","is_weekend","Customers","Sales"]:
    dfX[c] = dfX[c].astype("int32")

# Split temporal (80/20)
X = dfX.drop(columns=["Sales"])
y = dfX["Sales"]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, shuffle=False)

# Modelo base e espaço de busca
xgb_base = xgb.XGBRegressor(
    objective="reg:squarederror",
    tree_method="hist",
    random_state=SEED,
    n_jobs=-1
)

param_space = {
    "max_depth":         randint(4, 10),          # profundidade da árvore
    "learning_rate":     uniform(0.03, 0.15),     # eta
    "subsample":         uniform(0.6, 0.4),       # 0.6–1.0
    "colsample_bytree":  uniform(0.6, 0.4),       # 0.6–1.0
    "n_estimators":      randint(300, 900)        # número de árvores
}

# TimeSeriesSplit para evitar vazamento
tscv = TimeSeriesSplit(n_splits=3)

# RandomizedSearch leve (n_iter pequeno) — focado em RMSE
search = RandomizedSearchCV(
    estimator=xgb_base,
    param_distributions=param_space,
    n_iter=12,
    scoring="neg_root_mean_squared_error",
    cv=tscv,
    verbose=1,
    n_jobs=-1,
    random_state=SEED
)

# Treino e melhor conjunto
search.fit(X_train, y_train)
best_xgb = search.best_estimator_

print("\n Melhores hiperparâmetros:")
print(search.best_params_)
print("RMSE (CV) ~", -search.best_score_)

# Avaliação no holdout (20% final)
y_pred = best_xgb.predict(X_val)
mae  = mean_absolute_error(y_val, y_pred)
rmse = float(np.sqrt(mean_squared_error(y_val, y_pred)))
mape = float((np.abs((y_val - y_pred)/y_val).mean()) * 100)
r2   = r2_score(y_val, y_pred)

print("\n XGBoost Tunado — Holdout diário")
print(f"MAE : {mae:,.2f}")
print(f"RMSE: {rmse:,.2f}")
print(f"MAPE: {mape:.2f}%")
print(f"R²  : {r2:.3f}")

gc.collect();


Fitting 3 folds for each of 12 candidates, totalling 36 fits

🔧 Melhores hiperparâmetros:
{'colsample_bytree': np.float64(0.8080272084711243), 'learning_rate': np.float64(0.11200654190149194), 'max_depth': 9, 'n_estimators': 776, 'subsample': np.float64(0.9878338511058234)}
RMSE (CV) ~ 598.0998840332031

📊 XGBoost Tunado — Holdout diário
MAE : 349.57
RMSE: 507.22
MAPE: 5.55%
R²  : 0.971


**Melhores hiperparâmetros encontrados**

max_depth: 9

learning_rate: 0.112

n_estimators: 776

subsample: 0.988

colsample_bytree: 0.808

**Avaliação no holdout diário (20% final)**

MAE: 349,6

RMSE: 507,2

MAPE: 5,55%

R²: 0,971

**Interpretação rápida**

O tuning reduziu o RMSE em relação ao XGBoost baseline (612 → 507).

O MAPE caiu para aproximadamente 5,5%, tornando-o comparável ao Random Forest (5,94%) e até melhor em erro absoluto (MAE menor).

Ou seja, agora tem dois modelos de alto desempenho no granular diário: Random Forest e XGBoost Tunado, ambos entregando previsões com erro percentual médio em torno de 5–6%.

**Prox passo:**
identificar quais variáveis mais contribuíram para as previsões do XGBoost Tunado.
Usarei a importância por “gain” (ganho médio de informação) e mostrarei um gráfico de barras.
Como extra opcional, incluo um bloco SHAP em amostra pequena para interpretar direção/efeito.

In [ ]:
# Importâncias por "gain" (compatível com DataFrame ou numpy)
booster = best_xgb.get_booster()

# dicionário: {'feature_name': score, ...}  (pode ser 'f0','f1'... OU nomes reais)
gain_dict = booster.get_score(importance_type='gain')

# Descobrir a lista “oficial” de nomes que o modelo conhece
model_feat_names = booster.feature_names  # lista ou None
if model_feat_names is None:
    # fallback: tenta usar colunas do X_train (DataFrame)
    model_feat_names = list(getattr(X_train, "columns", [f"f{i}" for i in range(len(gain_dict))]))

# Montar DataFrame com as importâncias existentes
imp_df = pd.DataFrame(
    {"feature": list(gain_dict.keys()), "importance_gain": list(gain_dict.values())}
)

# Reindexar para incluir todas as features (as que não apareceram ganham 0)
imp_df = imp_df.set_index("feature").reindex(model_feat_names, fill_value=0).reset_index()
imp_df.columns = ["feature", "importance_gain"]

# Ordenar e exibir
imp_df = imp_df.sort_values("importance_gain", ascending=False).reset_index(drop=True)
print("Top 15 features (gain):")
display(imp_df.head(15))

# Gráfico
top = imp_df.head(15).iloc[::-1]
plt.figure(figsize=(9,5))
plt.barh(top["feature"], top["importance_gain"])
plt.title("Importância de Variáveis — XGBoost (gain)")
plt.xlabel("Importância (gain)")
plt.tight_layout()
plt.show()


Top 15 features (gain):


feature  importance_gain
0            Customers      260543072.0
1                Promo      122482376.0
2  CompetitionDistance       59690840.0
3                Store       34291356.0
4           is_weekend       24128808.0
5         StateHoliday       16039226.0
6            DayOfWeek       14838929.0
7                Month       10006752.0
8        SchoolHoliday        4091153.5
9                 Year        3633706.5

#Conclusão  

O presente estudo teve como objetivo o desenvolvimento de modelos de previsão de faturamento a partir do conjunto de dados **Rossmann Store Sales**, buscando aplicar técnicas de aprendizado de máquina e séries temporais em um problema real de negócios. O trabalho percorreu todo o ciclo de modelagem, desde a preparação e exploração dos dados, passando pela criação de baselines, até a avaliação de algoritmos avançados e análise do impacto de variáveis externas no desempenho das lojas.  

## Métodos Utilizados  

Diversas abordagens foram exploradas, contemplando diferentes paradigmas de modelagem:  

- **Baselines iniciais**:  
  Foram construídos modelos de referência como a Regressão Linear e o Naive Sazonal (lag-12). Esses métodos simples serviram para estabelecer parâmetros mínimos de comparação e avaliar se técnicas mais avançadas realmente trariam ganho de desempenho.  

- **Modelos supervisionados baseados em árvores**:  
  Foram aplicados algoritmos como **Árvore de Regressão**, **Random Forest** e **XGBoost**, devido à sua capacidade de capturar relações não lineares e interações entre variáveis categóricas e numéricas. O **XGBoost Tunado**, com otimização de hiperparâmetros, apresentou os melhores resultados no nível diário, alcançando **MAPE de 5,55% e R² de 0,97**, confirmando sua robustez em dados tabulares de grande volume.  

- **Modelos supervisionados lineares regularizados**:  
  Foi utilizada a **Regressão Ridge** aplicada em dados agregados mensais com variáveis de defasagem e sazonais. Esse modelo se mostrou particularmente eficaz para previsões em maior granularidade temporal, alcançando **erro semestral de apenas 2,37%**, destacando sua eficiência para análises estratégicas e consolidadas.  

- **Modelos de séries temporais clássicos**:  
  Técnicas como **ARIMA** e **SARIMA** também foram testadas. Apesar de conseguirem captar sazonalidade, sofreram limitações devido ao curto histórico disponível (25 meses de treino), o que comprometeu sua estabilidade e resultou em métricas inferiores aos modelos de aprendizado de máquina.  

## Resultados Obtidos  

- No nível **diário**, o **XGBoost Tunado** apresentou o melhor desempenho, com **MAE ≈ 350 mil, RMSE ≈ 507 mil, MAPE ≈ 5,55%** e **R² ≈ 0,97**, confirmando alta precisão na previsão de vendas diárias.  
- No nível **mensal**, a **Regressão Ridge** foi a mais equilibrada, alcançando **MAPE ≈ 5,4%** e **erro semestral de apenas 2,37%**.  
- As previsões consolidadas indicaram faturamento de aproximadamente **R$ 1,12 bilhão no semestre e R$ 2,34 bilhões no ano,** valores próximos ao observado, reforçando a confiabilidade dos modelos.  

## Variáveis de Maior Impacto  

A análise de importância de variáveis no **XGBoost** revelou que os principais fatores que impactam o faturamento são:  

- **Customers**: número de clientes foi a variável mais relevante, refletindo diretamente a demanda real.  
- **Promo**: a presença de promoções aumentou o faturamento médio diário em aproximadamente **+38,8%**, confirmando o impacto positivo de estratégias comerciais.  
- **Fins de semana**: elevaram as vendas em média **+18,3%**.  
- **Feriados**: apresentaram efeito negativo, reduzindo as vendas em torno de **-3,9%**.  
- **Competition Distance e Store Type**: também figuraram como fatores importantes, mostrando a influência do ambiente competitivo e das características estruturais de cada loja.  

## Conclusão Final  

Com base nos experimentos realizados, conclui-se que a combinação de modelos baseados em **árvores de decisão (XGBoost)** e regressões regularizadas (**Ridge**) oferece resultados consistentes e precisos para a previsão de faturamento no dataset Rossmann. Enquanto o XGBoost se destacou para previsões **granulares diárias**, a Regressão Ridge mostrou melhor adequação para previsões **consolidadas mensais e semestrais**.  

O estudo reforça a importância da utilização de múltiplas abordagens, da comparação com baselines e da análise de variáveis explicativas para garantir previsões confiáveis. Além disso, demonstrou-se que modelos de previsão podem apoiar a **tomada de decisão estratégica**, permitindo planejar estoques, promoções, metas comerciais e projeções financeiras com base em dados históricos e padrões de comportamento do consumidor.  


